// GENERATED by tools/gen_headers.py - DO NOT EDIT.
// Tier-1 gains: normalize 3400 RADIATED-BAND rms (250-8000 Hz
// passband of the current speaker (SPEAKER_BAND_HZ in tools/
// samplelib.py); energy outside it only loads the limiter) capped at
// 9000 peak. Re-run
// gen_all.sh after changing any Samples_src WAV (model tunables:
// tools/samplelib.py TUNABLES).
#pragma once
constexpr float kGain_bass1 = 0.2747f;
constexpr float kGain_jbass2 = 0.2834f;
constexpr float kGain_pad1 = 0.4226f;
constexpr float kGain_jpad1 = 0.2748f;
constexpr float kGain_pad3 = 0.3082f;
constexpr float kGain_bongo1 = 0.3427f;
constexpr float kGain_synth2 = 1.0648f;
constexpr float kGain_jbass1 = 0.2750f;
constexpr float kGain_jlead1 = 0.2976f;
constexpr float kGain_jlead2 = 0.2747f;
constexpr float kGain_bass2 = 0.5513f;
constexpr float kGain_guitar1 = 0.2800f;
constexpr float kGain_jlead3 = 0.2807f;
constexpr float kGain_jlead4 = 0.2747f;
constexpr float kGain_kick3 = 0.2747f;
constexpr float kGain_pad2 = 0.3976f;
constexpr float kGain_snareB3 = 0.3744f;
constexpr float kGain_synth1 = 0.3246f;
constexpr float kGain_synth3 = 0.2820f;
