#include "Voice.h"

#include <cmath>
#include <cstddef>
#include <iterator>
#include <span>
#include <utility>

// drums
#include "Samples/kick1.h"
#include "Samples/kick2.h"
#include "Samples/snareB2.h"
#include "Samples/snare1.h"
#include "Samples/snare2.h"
#include "Samples/snare3.h"
#include "Samples/snareB1.h"
#include "Samples/clap1.h"
#include "Samples/crash1.h"
#include "Samples/ride1.h"
#include "Samples/hihat1.h"
#include "Samples/hihat2.h"
// sfx
#include "Samples/sfx1.h"
#include "Samples/sfx2.h"
#include "Samples/sfx3.h"
#include "Samples/sfx4.h"
#include "Samples/sfx5.h"
#include "Samples/sfx6.h"
#include "Samples/sfx7.h"
#include "Samples/sfx8.h"
#include "Samples/sfx9.h"
#include "Samples/sfx10.h"
#include "Samples/sfx11.h"
#include "Samples/sfx12.h"
// pitched instruments
#include "Samples/bass1.h"
#include "Samples/jbass2.h"
#include "Samples/pad1.h"
#include "Samples/jpad1.h"
#include "Samples/pad3.h"
#include "Samples/bongo1.h"
#include "Samples/synth2.h"
#include "Samples/jlead2.h"
#include "Samples/jlead1.h"
#include "Samples/jbass1.h"
// instrument bank 1 (selectable with F4+D, then F1+note)
#include "Samples/bass2.h"
#include "Samples/guitar1.h"
#include "Samples/jlead3.h"
#include "Samples/jlead4.h"
#include "Samples/kick3.h"
#include "Samples/pad2.h"
#include "Samples/snareB3.h"
#include "Samples/synth1.h"
#include "Samples/synth3.h"
#include "SampleGains.h"

namespace {

// Source-normalization reference: stock samples peak near full scale; the
// instrument gains target this so one voice sits near the master knee
// (OutputMixer.h) and 2-4 voice sums reach into its soft region only on
// peaks. Drum/sfx readers apply this directly (sources peak ~32767).
constexpr float kSourceGain = 8000.0f / 32767.0f;
// Step-delay retrigger attenuation (Tracker echo cells).
constexpr float kStepDelayGain = 0.3f;
constexpr int32_t kOverdriveClipBound = 4000;
constexpr int32_t kHistoryStoreBound = 32767;
constexpr int kOptOctaveUseVoice = -1;

[[nodiscard]] constexpr int32_t ClampSample(int32_t value, int32_t bound) {
  return value > bound ? bound : (value < -bound ? -bound : value);
}

[[nodiscard]] constexpr int32_t ToIndex(std::size_t size) {
  return static_cast<int32_t>(size);
}

[[nodiscard]] float FinalizeSample(float sample, float volume, bool isDelay) {
  sample *= volume;
  if (isDelay) {
    sample *= kStepDelayGain;
  }
  return sample;
}

}  // namespace

// One call = one sample at kAudioSampleRate (see AudioConfig.h).
int32_t Voice::UpdateVoice() {
  int32_t sample = 0;
  switch (FamilyOf(voiceNum_)) {
    case InstrumentFamily::Pitched:
      sample = ReadWaveform();
      break;
    case InstrumentFamily::Sfx:
      sample = ReadSfxWaveform();
      break;
    case InstrumentFamily::Drum:
      sample = ReadDrumWaveform();
      break;
  }

  // Overdrive: clip first, then double, so output never exceeds +/- 8000.
  if (volume_ == 3) {
    sample = ClampSample(sample, kOverdriveClipBound) * 2;
  }

  // Record every dry sample so history taps are valid right after FX enable.
  UpdateHistory(sample);

  // Exactly one sample FX per voice; EffectMode::Off leaves the dry sample.
  // (Distinct from Tracker step-delay, which retriggers older grid cells.)
  switch (effectMode_) {
    case EffectMode::Lowpass8: {
      int32_t wet = 0;
      for (int tap = 0; tap < 8; tap++) {
        wet += GetHistorySample(tap);
      }
      sample = wet / 4;
      break;
    }
    case EffectMode::Lowpass4: {
      int32_t wet = 0;
      for (int tap = 0; tap < 4; tap++) {
        wet += GetHistorySample(tap);
      }
      sample = wet / 2;
      break;
    }
    case EffectMode::Echo: {
      float wet = 0.0f;
      for (int tap = 2; tap < 6; tap++) {
        wet += static_cast<float>(GetHistorySample(tap * 300)) /
               static_cast<float>(tap / 3 + 1);
      }
      sample = static_cast<int32_t>(wet);
      break;
    }
    case EffectMode::Off:
      break;
  }

  // Loudness contract: voices emit raw samples (~9000 peak at volume 1;
  // overdrive self-caps at 8000). Master limiter is the only nonlinearity.
  return sample;
}

int32_t Voice::ReadWaveform() {
  struct InstrumentSource {
    std::span<const int> data;
    float gain;
  };
  // RMS-normalized gains GENERATED by tools/gen_headers.py (SampleGains.h).
  // Target ~3400 RMS, peak <= 9000. Regenerate after any Samples_src change.
  static const InstrumentSource instrumentSources[] = {
      {bass1, kGain_bass1},     {jbass2, kGain_jbass2},
      {pad1, kGain_pad1},       {jpad1, kGain_jpad1},
      {pad3, kGain_pad3},       {bongo1, kGain_bongo1},
      {synth2, kGain_synth2},   {jbass1, kGain_jbass1},
      {jlead1, kGain_jlead1},   {jlead2, kGain_jlead2},
      // voiceNum 12-20: instrument bank 1.
      {bass2, kGain_bass2},     {guitar1, kGain_guitar1},
      {jlead3, kGain_jlead3},   {jlead4, kGain_jlead4},
      {kick3, kGain_kick3},     {pad2, kGain_pad2},
      {snareB3, kGain_snareB3}, {synth1, kGain_synth1},
      {synth3, kGain_synth3},
  };

  const int32_t voiceIndex = voiceNum_ - 2;
  if (voiceIndex < 0 ||
      std::cmp_greater_equal(voiceIndex, std::size(instrumentSources))) {
    return 0;
  }

  const auto &source = instrumentSources[voiceIndex];
  const int32_t sampleLen = ToIndex(source.data.size());
  sampleIndex_ = std::fmod(sampleIndex_, static_cast<float>(sampleLen));

  const int32_t index0 = static_cast<int32_t>(sampleIndex_);
  const int32_t index1 = (index0 + 1 >= sampleLen) ? 0 : index0 + 1;
  float sample =
      LerpSample(source.data[index0], source.data[index1],
                 sampleIndex_ - static_cast<float>(index0)) *
      source.gain;

  sampleIndex_ += baseFreq_;
  if (envelope_ > 0) {
    envelope_ -= kEnvelopeDecrementPerSample;
  }

  sample = FinalizeSample(sample * GetVolumeRatio(), volume_, isDelay_);
  return static_cast<int32_t>(sample);
}

int32_t Voice::ReadOneShotWaveform(std::span<const int> source) {
  const int32_t sampleLen = ToIndex(source.size());
  if (sampleIndex_ >= static_cast<float>(sampleLen)) {
    return 0;
  }

  int32_t subSampleIndex = static_cast<int32_t>(sampleIndex_);
  if (envelopeNum_ > 1) {
    subSampleIndex = sampleLen - subSampleIndex - 1;
  }

  float sample = static_cast<float>(source[subSampleIndex]);
  sampleIndex_ += (octave < 1) ? 1.0f : static_cast<float>(octave);

  sample = FinalizeSample(sample * kSourceGain, volume_, isDelay_);
  return static_cast<int32_t>(sample);
}

int32_t Voice::ReadDrumWaveform() {
  static const std::span<const int> drumSources[] = {
      kick1, snare1, snareB1, hihat1, kick2,  snare2,
      snare3, hihat2, snareB2, clap1,  crash1, ride1,
  };

  if (note_ < 0 || std::cmp_greater_equal(note_, std::size(drumSources))) {
    return 0;
  }
  return ReadOneShotWaveform(drumSources[note_]);
}

int32_t Voice::ReadSfxWaveform() {
  static const std::span<const int> sfxSources[] = {
      sfx1, sfx2, sfx3,  sfx4,  sfx5,  sfx6,
      sfx7, sfx8, sfx9,  sfx10, sfx11, sfx12,
  };

  if (note_ < 0 || std::cmp_greater_equal(note_, std::size(sfxSources))) {
    return 0;
  }
  return ReadOneShotWaveform(sfxSources[note_]);
}

float Voice::LerpSample(int32_t sampleA, int32_t sampleB, float ratio) {
  return static_cast<float>(sampleA) +
         static_cast<float>(sampleB - sampleA) * ratio;
}

float Voice::GetBaseFreq(int val, int ioctave) {
  // Equal-tempered playback ratio: one octave doubles the sample rate.
  const int semitones = val + ioctave * 12;
  return powf(2.0f, static_cast<float>(semitones) / 12.0f);
}

float Voice::GetVolumeRatio() {
  if (FamilyOf(voiceNum_) == InstrumentFamily::Drum) {
    return 1.0f;
  }
  const float envNorm =
      static_cast<float>(envelope_) / static_cast<float>(envelopeLength_);
  switch (envelopeNum_) {
    case 0: {
      float subVal = envNorm * 2.0f;
      return (subVal > 1.0f) ? 1.0f : subVal;
    }
    case 1: {
      // Gate off after a full envelope period.
      if ((1.0f - envNorm) >= 1.0f) {
        return 0.0f;
      }
      return 2.0f - envNorm * 2.0f;
    }
    case 2:
      return ((1.0f - envNorm) >= 1.0f) ? 0.0f : 1.0f;
    case 3: {
      if (envelope_ <= 0) {
        envelope_ = envelopeLength_;
      }
      const float env = (envNorm - 0.5f) * 2.0f;
      return 0.5f + std::abs(env) * 0.5f;
    }
    default:
      return 1.0f;
  }
}

void Voice::SetNote(int val, bool delay, int optOctave, int optInstrument) {
  // Reset playhead from the *incoming* instrument family, not the previous
  // voiceNum_. One-shots always restart; pitched keeps phase unless the
  // family changes either direction (drum/sfx <-> pitched).
  const InstrumentFamily incoming = FamilyOf(optInstrument);
  const InstrumentFamily previous = FamilyOf(voiceNum_);
  const bool familyChanged = (incoming != previous);
  const bool isOneShot = (incoming == InstrumentFamily::Drum ||
                          incoming == InstrumentFamily::Sfx);
  if (isOneShot || familyChanged) {
    sampleIndex_ = 0.0f;
  }

  note_ = val;
  envelope_ = envelopeLength_;
  voiceNum_ = optInstrument;
  const int octaveForPitch =
      (optOctave == kOptOctaveUseVoice) ? octave : optOctave;
  baseFreq_ = GetBaseFreq(val, octaveForPitch);
  isDelay_ = delay;
}

void Voice::SetDelay(int val) { delay = val; }

void Voice::SetVolume(int val) { volume_ = static_cast<float>(val); }

void Voice::SetOctave(int val) { octave = val; }

void Voice::SetEnvelopeNum(int val) { envelopeNum_ = val; }

void Voice::SetEnvelopeLength(int val) { envelopeLength_ = val; }

void Voice::SetEffectMode(EffectMode mode) { effectMode_ = mode; }

void Voice::UpdateHistory(int32_t sample) {
  sampleHistory_[sampleHistoryIndex_] =
      static_cast<int16_t>(ClampSample(sample, kHistoryStoreBound));
  sampleHistoryIndex_++;
  if (sampleHistoryIndex_ >= kSampleHistoryLength) {
    sampleHistoryIndex_ = 0;
  }
}

int32_t Voice::GetHistorySample(int backOffset) {
  int ind = sampleHistoryIndex_ - backOffset;
  if (ind < 0) {
    ind += kSampleHistoryLength;
  }
  return sampleHistory_[ind];
}
