#!/usr/bin/env python3
"""Header generation: Samples_src (loops/ preferred) -> Samples/*.h + SampleGains.h.

Everything here is a build artifact; delete and regenerate freely. Melodic
samples use their loop-prepped WAV when present; the gains header is
regenerated from the same PCM the firmware will hear, so adopting or
replacing a sample can never leave a stale hand-typed gain behind.
"""
import sys

import samplelib

def main():
    samplelib.HDR_DIR.mkdir(exist_ok=True)
    rows = []
    for name in samplelib.ALL:
        loop = samplelib.LOOP_DIR / f"{name}.wav"
        src = samplelib.SRC_DIR / f"{name}.wav"
        use = loop if loop.exists() else src
        if not use.exists():
            print(f"{name:10s} MISSING source, skipping header")
            continue
        vals = samplelib.read_wav(use)
        old_guard = "SAMPLES_" + name.upper() + "_H"
        hdr = samplelib.HDR_DIR / f"{name}.h"
        if hdr.exists():
            _, guard, _ = samplelib.load_header(hdr)
        else:
            guard = old_guard
        samplelib.write_header(hdr, name, guard, vals)
        if name in samplelib.MELODIC:
            peak, rms, wrms, gain = samplelib.stats(vals)
            rows.append((name, gain))
            print(f"{name:10s} {len(vals):6d} smp peak={peak:6d} "
                  f"rms={rms:6.0f} wrms={wrms:6.0f} gain={gain:.3f}")
        else:
            print(f"{name:10s} {len(vals):6d} smp (one-shot, kSourceGain path)")

    lo, hi = samplelib.SPEAKER_BAND_HZ
    lines = [
        "// GENERATED by tools/gen_headers.py - DO NOT EDIT.",
        f"// Tier-1 gains: normalize {samplelib.TARGET_WRMS:.0f} RADIATED-BAND rms "
        f"({lo:.0f}-{hi:.0f} Hz",
        "// passband of the current speaker (SPEAKER_BAND_HZ in tools/",
        "// samplelib.py); energy outside it only loads the limiter) capped at",
        f"// {samplelib.PEAK_CAP:.0f} peak. Re-run",
        "// gen_all.sh after changing any Samples_src WAV (model tunables:",
        "// tools/samplelib.py TUNABLES).",
        "#pragma once",
    ]
    for name, gain in rows:
        lines.append(f"constexpr float kGain_{name} = {gain:.4f}f;")
    (samplelib.HDR_DIR.parent / "SampleGains.h").write_text("\n".join(lines) + "\n")
    print(f"wrote SampleGains.h ({len(rows)} rows) + {len(samplelib.ALL)} headers")

if __name__ == "__main__":
    sys.exit(main())
